package raf.classycraft.app.model.elementDiagram;

public enum EditClassMode {
    ADD_ELEMENT, REMOVE_ELEMENT, RENAME_CLASS_NAME,RENAME_ELEMENT,CHANGE_ELEMENT_TYPE, CHANGE_ELEMENT_VISIBILITY, MODIFY_STATIC_ABSTRACT;
}
