package raf.classycraft.app.model.messageGenerator;

public enum EventTypes {
    NODE_CANNOT_BE_DELETED,
    NAME_CANNOT_BE_EMPTY,
    PROJECTEXPLORER_CANNOT_BE_DELETED,
    NODE_MUST_BE_SELECTED,
    PROJECTEXPLORER_CANNOT_BE_RENAMED,
    NODE_WILL_BE_DELETED,
    ONLY_PROJECT_HAS_AUTHOR,
    NODE_SUCCESSFULLY_RENAMED,

    NODE_SUCCESSFULLY_DELETED





}
